version: '3.8'
services:
  backend:
    container_name: backend-container
    restart: always
    build: ./backend
    ports: 
      - "8000:8000"
  frontend:
    container_name: frontend-container
    restart: always
    build: ./frontend
    ports: 
      - "3000:3000"