---
swagger: '2.0'
info:
  title: INVENTARIS API V1
  version: v1
paths:
  "/login":
    post:
      summary: Login
      tags:
      - Authentication
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              example: simbada@gmail.com
            password:
              type: string
              example: '12345678'
          required: []
      responses:
        '201':
          description: Successfull
          schema:
            type: object
        '422':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Email is Already Taken
              code:
                type: string
                example: '422'
        '500':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Header
              code:
                type: string
                example: X-401
  "/v1/user/registrasi/create":
    post:
      summary: Create User
      tags:
      - Registrasi
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              example: simbada@gmail.com
            password:
              type: string
              example: '12345678'
            password_confirmation:
              type: string
              example: '12345678'
            user_role:
              type: string
              example: SuperAdmin
            nama:
              type: string
              example: Admin Simbada
            nip:
              type: string
              example: '019231234329102'
            telepon:
              type: string
              example: '081232132318'
          required: []
      responses:
        '201':
          description: Successfull
          schema:
            type: object
        '422':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Email is Already Taken
              code:
                type: string
                example: '422'
        '500':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Header
              code:
                type: string
                example: X-401
  "/v1/user/registrasi/find":
    post:
      summary: Find User
      tags:
      - Registrasi
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      - name: body
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              example: tatang@polban.ac.id
          required: []
      responses:
        '200':
          description: Successfull
          schema:
            type: object
        '422':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: User tidak ditemukan!
              code:
                type: string
                example: '422'
        '500':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Header
              code:
                type: string
                example: X-401
  "/v1/user/registrasi/edit":
    post:
      summary: Edit User
      tags:
      - Registrasi
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      - name: body
        in: body
        schema:
          type: object
          properties:
            id:
              type: string
              example: 636cfd59e21fac2ab08223c3
            email:
              type: string
              example: simbada@gmail.com
            user_role:
              type: string
              example: SuperAdmin
            nama:
              type: string
              example: Admin Simbada
            nip:
              type: string
              example: '019231234329102'
            telepon:
              type: string
              example: '081232132318'
          required: []
      responses:
        '200':
          description: Successfull
          schema:
            type: object
        '422':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: User tidak ditemukan!
              code:
                type: string
                example: '422'
        '500':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Header
              code:
                type: string
                example: X-401
  "/v1/user/registrasi/delete":
    post:
      summary: Delete User
      tags:
      - Registrasi
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      - name: body
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
              example: simbada@gmail.com
          required: []
      responses:
        '200':
          description: Successfull
          schema:
            type: object
        '422':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: User tidak ditemukan!
              code:
                type: string
                example: '422'
        '500':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Header
              code:
                type: string
                example: X-401
  "/v1/user/registrasi/findAll":
    get:
      summary: Find All User
      tags:
      - Registrasi
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      responses:
        '200':
          description: Successfull
          schema:
            type: object
        '422':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: User tidak ditemukan!
              code:
                type: string
                example: '422'
        '500':
          description: Error
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid Header
              code:
                type: string
                example: X-401
